### ISSUE TITLE
Atmosphere Meter On Boost/ECOM Falling Faster Than In Game

### ISSUE THREAD

**Issue by LiamO32** [tcannonfodder/houston#10]
The Atmosphere meter on the Boost/ECOM page will fall much faster than it does in game. It seems that as the atmosphere meter in game is half way, the atmosphere meter on Houston is all the way down to nothing.

Images below are taken at the exact same time in a KSP launch.

http://imgur.com/a/S80kh

**Comment by tcannonfodder** [comment]
Still needs more investigation, though acceptable for a 1.0 release.
